secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception_network


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nde-chab/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nde-chab/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge

